### ISSUE TITLE
KeyError: 'default'

### ISSUE THREAD

**Issue by lujiayou123** [jonasrothfuss/ProMP#4]
python experiments/all_envs_eval/trpo_run_all.py 

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "experiments/all_envs_eval/trpo_run_all.py", line 138, in <module>
    run_sweep(run_experiment, sweep_params, EXP_NAME, INSTANCE_TYPE)
  File "/home/ljy/文档/ProMP-full_code/experiment_utils/run_sweep.py", line 27, in run_sweep
    local_output_dir=os.path.join(config.DATA_DIR, 'local', exp_name))
  File "/home/ljy/文档/ProMP-full_code/doodad/doodad/easy_sweep/launcher.py", line 38, in __init__
    self.mount_out_s3 = mount.MountS3(s3_path='exp_logs', mount_point=docker_output_dir, output=True)
  File "/home/ljy/文档/ProMP-full_code/doodad/doodad/mount.py", line 99, in __init__
    s3_bucket = AUTOCONFIG.s3_bucket()
  File "/home/ljy/文档/ProMP-full_code/doodad/doodad/ec2/autoconfig.py", line 16, in s3_bucket
    return self.config['default']['s3_bucket_name']
  File "/home/ljy/anaconda3/envs/mujoco-py/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'default'

What maybe the cause?

**Comment by jonasrothfuss** [comment]
You have to properly setup doodad. See [https://github.com/jonasrothfuss/doodad](https://github.com/jonasrothfuss/doodad) for how do to the setup. Based on your specification during setup, it should create a config.ini file which e.g. specifies the AWS S3 bucket, in which your experiment results will be saved.
